create table if not exists public.lancamentos (
  id bigint generated by default as identity primary key,
  company text not null,
  nfe text,
  nf_value text,
  boletos text,
  receipt text,
  due text not null,
  value numeric default 0,
  status text default 'Pendente',
  owner text,
  notes text,
  created_at timestamptz default now()
);

alter table public.lancamentos enable row level security;
create policy "Acesso público aos lançamentos" on public.lancamentos for all using (true) with check (true);
